#!/usr/bin/env python
import re, sys, os, commands, socket, getpass
"""
Trying to generate prefix sets automatically. not pretty. for NHN.
"""

# These have been queried, do not re-query - do not loop.
G_WHOIS = []
G_ASSET_MEMBERS = []
G_WHOIS_OUT = {}
DB_HITS = 0

def getRoutes(asn):
    prefixes = []
    out = dowhois("""-i origin %s""" % asn)
    for l in out.split("\n"):
        if l[0:5] == 'route':
            route = l.replace('route6', 'route').split('route:')[1].strip().split(" ")[0].strip()
            gele = ''
            pfx = """%s ge %s,""" % (route.strip(), route.split('/')[1].strip())
            prefixes.append(pfx)

    return prefixes

def isAsn(asn):
    asn = asn.strip()
    m = re.search('AS[0-9]{1,8}', asn)
    if m != None:
        return True
    else:
        return False

def isAsSet(asn):
    asn = asn.strip()
    m = re.search('AS-.+', asn)
    if m != None:
        return True
    else:
        return False

def domemberwhois (query):
    whois = dowhois(query)
    members = []

    for l in whois.split("\n"):
        m = re.search('^members: (.+)', l)
        if m != None:
            member = m.group(1).strip().split(" ")[0]
            members.append(member)

    return members


def getAsSets(asset):
    as_sets = [asset]
    queried = []

    print """ # script imports %s""" % as_sets[0]

    while len(as_sets) > 0:
        if as_sets[0] not in queried:
            queried.append(as_sets[0])
            members = domemberwhois(as_sets[0])
            for m in members:
                if isAsSet(m):
                    as_sets.append(m)
                    print """ # %s imports %s""" % (as_sets[0], m)

            as_sets.pop(0)
        else:
            as_sets.pop(0)

    return queried

def isok (query):
    global G_WHOIS
    if query in G_WHOIS:
        return False
    else:
        G_WHOIS.append(query)
        return True

def dowhois (query):
    global G_WHOIS_OUT, DB_HITS
    if isok(query):
        out = commands.getoutput("""whois -h whois.ripe.net %s""" % (query))
        DB_HITS += 1
        G_WHOIS_OUT[query] = out
    else:
        out = G_WHOIS_OUT[query]

    return out

#def getImports (ASSET):


def getRoutesFromAS(ASN):
    if ASN[0:2] != 'AS':
        ASN = ("""AS%s""" % ASN)

if __name__ == '__main__':
    getRoutesFromAS("34087")

    if len(sys.argv) == 1:
        print("""Usage: %s AS-SET""" % (sys.argv[0]))
        sys.exit(1)

    origin = sys.argv[1]

    print
    print """prefix-set PS_%s""" % (origin)
    print """ # Autogenerated by %s by %s@%s""" % (sys.argv[0], getpass.getuser(), socket.gethostname())

    # First, get all other AS-SET imports (and AS-members of these)
    as_sets = getAsSets(origin)
    for asset in as_sets:
        members = domemberwhois(asset)
        for m in members:
            if isAsn(m):
                print """ #GROUP %s %s""" % (asset, m)
                pfxs = getRoutes(m)
                for pfx in pfxs:
                    print """ %s""" % pfx

    print """ #END"""
    print """end-set"""

    print """ # Statistics: %d RIPE DB HITS""" % DB_HITS
